---
- name: Ensure procps is installed.
  package:
    name: "{{ procps_package }}"
    state: present
  when: >
    ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10

- name: Enable needed modules
  community.general.modprobe:
    name: "{{ mod_item }}"
    state: present
    persistent: present
  loop:
    - br_netfilter
    - overlay
  loop_controls:
    loop_var: mod_item

# See: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#letting-iptables-see-bridged-traffic
- name: Let iptables see bridged traffic.
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward
  when: >
    ansible_distribution != 'Debian'
    or ansible_distribution_major_version | int < 10
